CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email text NOT NULL,
	username text NOT NULL,
	"password" text NOT NULL,
	log_state bool NULL DEFAULT false,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.boards (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int4 NULL,
	board_title text NOT NULL,
	times_played int4 NOT NULL,
	date_created timestamp NULL,
	date_updated timestamp NULL,
	category_one text NULL,
	category_two text NULL,
	category_three text NULL,
	category_four text NULL,
	category_five text NULL,
	category_six text NULL,
	CONSTRAINT boards_pkey PRIMARY KEY (id)
);


CREATE TABLE public.communityBoards (
	id int4 NOT NULL,
	user_id int4 NULL,
	board_title text NOT NULL,
	likes int4 NOT NULL,
	date_created timestamp NULL,
	category_two text NOT NULL,
	category_four text NOT NULL,
	category_three text NOT NULL,
	category_five text NOT NULL,
	category_six text NOT NULL,
	category_one text NOT NULL
);


CREATE TABLE public.questions (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	board_id int4 NULL,
	question_text text NOT NULL,
	question_answer text NOT NULL,
	question_points int4 NOT NULL,
	question_category int4 NOT NULL,
	CONSTRAINT questions_pkey1 PRIMARY KEY (id)
);

CREATE TABLE public.supports (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int4 NULL,
	email text NOT NULL,
	subject text NOT NULL,
	"content" text NOT NULL,
	CONSTRAINT supports_pkey PRIMARY KEY (id)
);
