CREATE TABLE boards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    board_title TEXT NOT NULL,
    times_played INTEGER NOT NULL,
    date_created TIMESTAMP,
    date_updated TIMESTAMP
);