CREATE TABLE questions(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    board_id INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    question_answer TEXT NOT NULL,
    question_points INTEGER NOT NULL,
    question_category TEXT NOT NULL
);